# Generated by Django 2.1.7 on 2019-10-19 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191019_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'MySubscriber', 'verbose_name_plural': 'a lot of Subscribers'},
        ),
    ]
