# Generated by Django 3.0 on 2019-12-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_productinbasket_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='nmb',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='nmb',
            new_name='number',
        ),
    ]
