# Generated by Django 3.0 on 2019-12-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191214_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='number',
            new_name='nmb',
        ),
        migrations.RenameField(
            model_name='productinorder',
            old_name='number',
            new_name='nmb',
        ),
    ]
