# Generated by Django 3.0 on 2019-12-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='order_user',
        ),
    ]
